### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Luna5-threshold**
Create the security policy for this repository

### CODE REVIEW

**Review by derekpierre — DISMISSED** [review]
🎸

**Comment by r-czajkowski** [comment]
@Luna5-threshold thanks for opening a PR! Please run `yarn format:fix` to fix linting errors in `security.md` file.

**Comment by Luna5-threshold** [comment]
> @Luna5-threshold thanks for opening a PR! Please run `yarn format:fix` to fix linting errors in `security.md` file.

This is no code file, I don't really know which type of format would be missing. Can you help?

**Comment by r-czajkowski** [comment]
> > @Luna5-threshold thanks for opening a PR! Please run `yarn format:fix` to fix linting errors in `security.md` file.
> 
> This is no code file, I don't really know which type of format would be missing. Can you help?

We format `.md` files as well. You need to install dependencies `yarn install --ignore-scripts` and then format `yarn format:fix`.

**Review by cygnusv — APPROVED** [review]

**Pull request merged**
